# Need help with exception.
try:
    int("a")
except ValueError as e:
    print("Something quite not write!!! \n", e)

print("End of program")
